name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse:4.5.2
    
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev default-jdk

      - name: Install R package dependencies
        run: |
          Rscript -e 'install.packages(c("remotes","devtools","testthat","knitr","rmarkdown","dplyr","tidyr"))'
          Rscript -e 'remotes::install_version("sparklyr", version = "1.8.0")'

      - name: Build and Check package
        run: |
          R CMD build . --no-manual
          R CMD check *.tar.gz --no-manual --as-cran

      - name: Run tests
        run: |
          Rscript -e "library(testthat); test_dir('tests/testthat')"
